### ISSUE TITLE
Return status code 400 for failure instead of 403

### ISSUE THREAD

**Issue by jwbambacht** [cldme/aws-lambda#13]
For instance when adding credit without supplying user_id or amount

**Comment by tomdevman** [comment]
We can look into this, but I'm not sure we can change it, since it has to do with the API Gateway probably, anyways I don't think it should matter too much that we return 403 instead of 400 for a route that is incorrect (it matters only for the specified routes that we indeed return 400 in case of failure or 200 otherwise)

**Comment by jwbambacht** [comment]
If they do a particular check for 400 and it returns a 403, they may label these situations as faulty. So maybe good to also check this with the teachers.

**Comment by jwbambacht** [comment]
Any status code between 400 and 500 is fine
